[package]
name = "realsense-rust"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
realsense-sys = { version = "^0.1.0", path = "realsense-sys" }
num-derive = "^0.3.0"
num-traits = "^0.2.11"
nalgebra = "^0.19.0"
